# Generated by Django 3.0.4 on 2020-04-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('client_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('cell_technology', models.CharField(max_length=30)),
                ('cell_manufacturer', models.CharField(max_length=30)),
                ('number_cells', models.IntegerField()),
                ('number_cells_series', models.IntegerField()),
                ('number_series', models.IntegerField()),
                ('number_diodes', models.IntegerField()),
                ('product_length', models.DecimalField(decimal_places=4, max_digits=30)),
                ('product_width', models.DecimalField(decimal_places=4, max_digits=30)),
                ('product_weight', models.DecimalField(decimal_places=4, max_digits=30)),
                ('superstrate_type', models.CharField(max_length=30)),
                ('superstrate_manufacturer', models.CharField(max_length=30)),
                ('substrate_type', models.CharField(max_length=30)),
                ('substrate_manufacturer', models.CharField(max_length=30)),
                ('frame_type', models.CharField(max_length=30)),
                ('frame_adhesive', models.CharField(max_length=30)),
                ('encapsulant_type', models.CharField(max_length=30)),
                ('encapsulant_manufacturer', models.CharField(max_length=30)),
                ('junction_box_type', models.CharField(max_length=30)),
                ('junction_box_manufacturer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='anon', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(default='password', max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('prefix', models.CharField(max_length=3)),
                ('job_title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('office_phone', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('client_name', models.ForeignKey(default='company', on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('is_fi_required', models.BooleanField()),
                ('fi_frequency', models.DecimalField(decimal_places=4, max_digits=30)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.DecimalField(decimal_places=4, max_digits=30)),
                ('voc', models.DecimalField(decimal_places=4, max_digits=30)),
                ('isc', models.DecimalField(decimal_places=4, max_digits=30)),
                ('vmp', models.DecimalField(decimal_places=4, max_digits=30)),
                ('imp', models.DecimalField(decimal_places=4, max_digits=30)),
                ('pmp', models.DecimalField(decimal_places=4, max_digits=30)),
                ('ff', models.DecimalField(decimal_places=4, max_digits=30)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product')),
                ('sequence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=30)),
                ('address_2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('fax_number', models.CharField(max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('certificate_id', models.IntegerField()),
                ('report_number', models.IntegerField()),
                ('issue_date', models.DateTimeField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Location')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestStandard')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.User')),
            ],
        ),
    ]
