# Generated by Django 3.0.4 on 2020-05-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='CL', max_length=2),
        ),
    ]
