# Generated by Django 3.0.4 on 2020-05-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0003_auto_20200501_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teststandard',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
