# Generated by Django 3.0.4 on 2020-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0004_auto_20200501_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=30),
        ),
    ]
